kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: EeeTECHfu2sJZQpicYjwhCpi6QsmE3Br0nTvAVRUvus=
      - identity: {}
